### ISSUE TITLE
Various ideas

### ISSUE THREAD

**Issue by hazadus** [hazadus/ts-particle-text#1]
## ToDos

- [ ] add fps counter / particle count
- [ ] calculate `gap` depending on canvas size
- [ ] calculate `mouse.radius` depending on canvas size
- [ ] handle `resize` event
